id: A0A075EC9
title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the Everpresent
  Gurus'
type: translation
pechas:
- I4B0BD9A9
- I8FF0F3E1
- I5AF9B655
- I67FFA78A
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:32:14.467275
  last_modified_at: 2023-01-04 12:32:14.467288
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I4B0BD9A9/E1EA: '5147'
  I8FF0F3E1/C82B: '5147'
  I5AF9B655/CC99: '5147'
  I67FFA78A/3FF5: '5147'
